### ISSUE TITLE
Addgene resource

### ISSUE THREAD

**Issue by mattodd** [OpenSourceSarsCoV2/LivingResourceReview#3]
As per https://twitter.com/Addgene/status/1310511922161291264
add: https://www.addgene.org/collections/covid-19-resources/
to physical resources section of the paper/wiki.

**Comment by danaklug** [comment]
Addgene [wiki page](https://github.com/OpenSourceSarsCoV2/LivingResourceReview/wiki/Sample-Sharing%3A-Addgene) has been added.
